version: '3.1'
services:

  wordpress:
    container_name: Wordpress
    image: wordpress
    restart: always
    ports:
      - 90:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - c:/docker/configuracion/db-wordpress:/var/www/html

  db:
    container_name: Wordpress-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - c:/docker/configuracion/mysql:/var/lib/mysql

